package com.finora.api.transaction;

import com.finora.api.account.Account;
import com.finora.api.category.Category;
import com.finora.api.common.persistence.AuditableEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDate;

@Entity
@Table(name = "transactions")
public class Transaction extends AuditableEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false, updatable = false)
    private Long userId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private TransactionType type;

    @Column(nullable = false, precision = 14, scale = 2)
    private BigDecimal amount;

    @Column(nullable = false, length = 200)
    private String description;

    @Column(name = "occurred_on", nullable = false)
    private LocalDate occurredOn;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "account_id")
    private Account account;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", length = 20)
    private PaymentMethod paymentMethod;

    /**
     * True only for CREDIT transactions created before the credit-card domain
     * existed. They are preserved as plain historical expenses, disconnected
     * from any card or invoice; new generic CREDIT transactions are rejected.
     * Set exclusively by migration V7 — never by application code.
     */
    @Column(name = "legacy_credit", nullable = false, insertable = false, updatable = false)
    private boolean legacyCredit;

    /**
     * FALSE only while an ACTIVE legacy-credit conversion replaces this
     * transaction as the expense source (the generated card installments take
     * over). The row stays visible as an audit record; every financial
     * aggregate filters on this flag. Maintained exclusively by the
     * conversion engine — reversal restores TRUE.
     */
    @Column(name = "financially_active", nullable = false)
    private boolean financiallyActive = true;

    /** Set when this transaction executed a wishlist item (idempotency anchor). */
    @Column(name = "wishlist_item_id", updatable = false)
    private Long wishlistItemId;

    /** Set when this transaction was generated by a recurring occurrence. */
    @Column(name = "commitment_id", updatable = false)
    private Long commitmentId;

    /**
     * Set when this transaction was materialized from a statement-import
     * item. A partial unique index guarantees at most one live transaction
     * per item — the idempotency backstop of import confirmation.
     */
    @Column(name = "statement_import_item_id", updatable = false)
    private Long statementImportItemId;

    @Column(columnDefinition = "text")
    private String notes;

    protected Transaction() {
    }

    public Transaction(Long userId, TransactionType type, BigDecimal amount, String description,
                       LocalDate occurredOn, Category category) {
        this.userId = userId;
        this.type = type;
        this.amount = amount;
        this.description = description;
        this.occurredOn = occurredOn;
        this.category = category;
    }

    public Long getId() {
        return id;
    }

    public Long getUserId() {
        return userId;
    }

    public TransactionType getType() {
        return type;
    }

    public void setType(TransactionType type) {
        this.type = type;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDate getOccurredOn() {
        return occurredOn;
    }

    public void setOccurredOn(LocalDate occurredOn) {
        this.occurredOn = occurredOn;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public boolean isLegacyCredit() {
        return legacyCredit;
    }

    public boolean isFinanciallyActive() {
        return financiallyActive;
    }

    public void setFinanciallyActive(boolean financiallyActive) {
        this.financiallyActive = financiallyActive;
    }

    public Long getWishlistItemId() {
        return wishlistItemId;
    }

    public Long getCommitmentId() {
        return commitmentId;
    }

    public void setCommitmentId(Long commitmentId) {
        this.commitmentId = commitmentId;
    }

    public void setWishlistItemId(Long wishlistItemId) {
        this.wishlistItemId = wishlistItemId;
    }

    public Long getStatementImportItemId() {
        return statementImportItemId;
    }

    public void setStatementImportItemId(Long statementImportItemId) {
        this.statementImportItemId = statementImportItemId;
    }
}
