import type { PaymentMethod, TransactionType } from '../shared/types'

export type CommitmentCadence = 'WEEKLY' | 'MONTHLY' | 'YEARLY'
export type ExecutionMode = 'MANUAL' | 'AUTOMATIC'
export type RecurrenceTarget = 'PROJECTION_ONLY' | 'ACCOUNT_TRANSACTION' | 'CREDIT_CARD_PURCHASE'
export type OccurrenceStatus = 'SCHEDULED' | 'MATERIALIZED' | 'SKIPPED' | 'FAILED' | 'REVERSED'

export const CADENCE_LABELS: Record<CommitmentCadence, string> = {
  WEEKLY: 'Semanal',
  MONTHLY: 'Mensal',
  YEARLY: 'Anual',
}

export const TARGET_LABELS: Record<RecurrenceTarget, string> = {
  PROJECTION_ONLY: 'Somente planejamento',
  ACCOUNT_TRANSACTION: 'Lançamento em conta',
  CREDIT_CARD_PURCHASE: 'Compra no cartão',
}

export const OCCURRENCE_STATUS_LABELS: Record<OccurrenceStatus, string> = {
  SCHEDULED: 'Agendada',
  MATERIALIZED: 'Executada',
  SKIPPED: 'Pulada',
  FAILED: 'Falhou',
  REVERSED: 'Estornada',
}

export interface Commitment {
  id: number
  description: string
  amount: number
  category: { id: number; name: string; type: TransactionType }
  cadence: CommitmentCadence
  dueDay: number | null
  startDate: string
  endDate: string | null
  active: boolean
  paymentMethod: PaymentMethod | null
  nextDueDate: string | null
  executionMode: ExecutionMode
  targetKind: RecurrenceTarget
  accountId: number | null
  accountName: string | null
  creditCardId: number | null
  creditCardName: string | null
  installmentCount: number
  legacyProjectionOnly: boolean
  failedOccurrences: number
}

export interface CommitmentRequest {
  description: string
  amount: number
  categoryId: number
  cadence: CommitmentCadence
  dueDay?: number | null
  startDate: string
  endDate?: string | null
  active?: boolean
  paymentMethod?: PaymentMethod | null
  executionMode?: ExecutionMode
  targetKind?: RecurrenceTarget
  accountId?: number | null
  creditCardId?: number | null
  installmentCount?: number | null
}

export interface Occurrence {
  commitmentId: number
  scheduledDate: string
  effectiveDate: string
  status: OccurrenceStatus
  persisted: boolean
  autoGenerated: boolean
  transactionId: number | null
  cardPurchaseId: number | null
  failureCode: string | null
  failureMessage: string | null
  materializedAt: string | null
  reversedAt: string | null
}

export interface OccurrencePreview {
  from: string
  to: string
  occurrences: Occurrence[]
}

export interface ProcessDueResult {
  materialized: number
  failed: number
  alreadyProcessed: number
}

export interface UpcomingCommitments {
  from: string
  to: string
  totalAmount: number
  items: Array<{
    commitmentId: number
    description: string
    amount: number
    category: { id: number; name: string; type: TransactionType }
    dueDate: string
    paymentMethod: PaymentMethod | null
  }>
}
