package com.finora.api.legacyconversion;

/** Presentation state of one legacy-credit row in the conversion inventory. */
public enum ConversionInventoryState {
    /** Convertible now (includes sources whose previous conversion was reversed). */
    ELIGIBLE,
    /** An ACTIVE conversion exists; the card purchase is the expense source. */
    CONVERTED,
    /** The latest conversion was reversed; the source is active and convertible again. */
    REVERSED,
    /** Legacy credit, but a rule prevents conversion (e.g. generated by a recurring). */
    BLOCKED
}
