package com.finora.api.offlinesync;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.List;
import java.util.UUID;
import tools.jackson.databind.JsonNode;

/**
 * Wire contract for replaying offline mutations.
 *
 * <p>The envelope is deliberately typed and closed: the client submits a
 * resource type, an operation, a target and a payload — never an HTTP method, a
 * route, a class name, a repository, SQL or a user id. Ownership always comes
 * from the authenticated session.
 */
public final class OfflineSyncDtos {

    /** Default replay batch the client aims for. */
    public static final int DEFAULT_BATCH_SIZE = 20;

    /** Hard upper bound; a larger batch is rejected before any processing. */
    public static final int MAX_BATCH_SIZE = 25;

    /** Serialized size ceiling for one mutation payload. */
    public static final int MAX_PAYLOAD_BYTES = 64 * 1024;

    /** Serialized size ceiling for the whole batch payload set. */
    public static final int MAX_BATCH_PAYLOAD_BYTES = 512 * 1024;

    private OfflineSyncDtos() {
    }

    public record MutationBatchRequest(
            @NotEmpty(message = "Informe ao menos uma operação.")
            @Size(max = MAX_BATCH_SIZE, message = "Envie no máximo " + MAX_BATCH_SIZE + " operações por lote.")
            @Valid
            List<MutationEnvelope> mutations) {
    }

    /**
     * One queued mutation.
     *
     * @param clientMutationId stable idempotency key generated by the client
     * @param baseVersion      the optimistic version the offline edit saw;
     *                         required for UPDATE and DELETE, absent for CREATE
     */
    public record MutationEnvelope(
            @NotNull(message = "Informe o identificador da operação.")
            UUID clientMutationId,

            @NotNull(message = "Informe o tipo de recurso.")
            SyncResourceType resourceType,

            @NotNull(message = "Informe a operação.")
            SyncOperation operation,

            @NotNull(message = "Informe o alvo da operação.")
            @Valid
            ResourceTarget target,

            Long baseVersion,

            @NotNull(message = "Informe os dados da operação.")
            JsonNode payload) {
    }

    /**
     * Exactly one identity: a server id for a resource that already exists, or
     * the client id of a resource created offline. Both at once is rejected —
     * an ambiguous target could be resolved two different ways.
     */
    public record ResourceTarget(Long serverId, UUID clientResourceId) {
    }

    public record MutationBatchResponse(List<MutationResult> results) {
    }

    /**
     * One result per input mutation, in submission order. Only the fields that
     * apply to the status are populated.
     */
    public record MutationResult(
            UUID clientMutationId,
            SyncResourceType resourceType,
            SyncOperation operation,
            SyncStatus status,
            UUID clientResourceId,
            Long resourceId,
            Long version,
            /** Minimal typed representation the client needs to update its cache. */
            JsonNode result,
            ConflictDetail conflict,
            ErrorDetail error) {

        static MutationResult applied(MutationEnvelope envelope, UUID clientResourceId,
                                      Long resourceId, Long version, JsonNode result) {
            return new MutationResult(envelope.clientMutationId(), envelope.resourceType(),
                    envelope.operation(), SyncStatus.APPLIED, clientResourceId, resourceId,
                    version, result, null, null);
        }

        static MutationResult alreadyApplied(MutationEnvelope envelope, UUID clientResourceId,
                                             Long resourceId, Long version, JsonNode result) {
            return new MutationResult(envelope.clientMutationId(), envelope.resourceType(),
                    envelope.operation(), SyncStatus.ALREADY_APPLIED, clientResourceId,
                    resourceId, version, result, null, null);
        }

        static MutationResult conflict(MutationEnvelope envelope, ConflictDetail conflict) {
            return new MutationResult(envelope.clientMutationId(), envelope.resourceType(),
                    envelope.operation(), SyncStatus.CONFLICT,
                    envelope.target().clientResourceId(), envelope.target().serverId(),
                    null, null, conflict, null);
        }

        static MutationResult rejected(MutationEnvelope envelope, ErrorDetail error) {
            return new MutationResult(envelope.clientMutationId(), envelope.resourceType(),
                    envelope.operation(), SyncStatus.REJECTED,
                    envelope.target().clientResourceId(), envelope.target().serverId(),
                    null, null, null, error);
        }

        static MutationResult dependencyMissing(MutationEnvelope envelope, ErrorDetail error) {
            return new MutationResult(envelope.clientMutationId(), envelope.resourceType(),
                    envelope.operation(), SyncStatus.DEPENDENCY_MISSING,
                    envelope.target().clientResourceId(), envelope.target().serverId(),
                    null, null, null, error);
        }
    }

    /**
     * A conflict the user must resolve. The server snapshot is the same public
     * representation the resource's own endpoint returns — it never carries
     * owner ids, receipt internals, session data or raw entity serialization.
     */
    public record ConflictDetail(
            ConflictType conflictType,
            Long localBaseVersion,
            Long serverVersion,
            JsonNode serverSnapshot,
            List<ResolutionOption> resolutionOptions,
            /** Safe Portuguese explanation shown next to the comparison. */
            String detail) {
    }

    public record ErrorDetail(
            String code,
            String detail,
            List<FieldError> fieldErrors) {

        static ErrorDetail of(String code, String detail) {
            return new ErrorDetail(code, detail, List.of());
        }
    }

    public record FieldError(String field, String message) {
    }
}
