package com.finora.api.commitment.occurrence;

import com.finora.api.commitment.Commitment;
import com.finora.api.common.persistence.AuditableEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.Instant;
import java.time.LocalDate;

/**
 * One auditable occurrence of a recurring definition. Its identity is the
 * pair (commitment, original scheduled date) — unique in the database — so
 * generation, catch-up, retries and concurrent processors always converge on
 * the same row. Rescheduling moves only {@code effectiveDate}; the identity
 * date never changes.
 */
@Entity
@Table(name = "commitment_occurrences")
public class CommitmentOccurrence extends AuditableEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false, updatable = false)
    private Long userId;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "commitment_id", nullable = false, updatable = false)
    private Commitment commitment;

    @Column(name = "scheduled_date", nullable = false, updatable = false)
    private LocalDate scheduledDate;

    @Column(name = "effective_date", nullable = false)
    private LocalDate effectiveDate;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private OccurrenceStatus status;

    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated;

    @Column(name = "transaction_id")
    private Long transactionId;

    @Column(name = "card_purchase_id")
    private Long cardPurchaseId;

    @Column(name = "failure_code", length = 60)
    private String failureCode;

    @Column(name = "failure_message", length = 300)
    private String failureMessage;

    @Column(name = "materialized_at")
    private Instant materializedAt;

    @Column(name = "reversed_at")
    private Instant reversedAt;

    protected CommitmentOccurrence() {
    }

    public CommitmentOccurrence(Long userId, Commitment commitment, LocalDate scheduledDate) {
        this.userId = userId;
        this.commitment = commitment;
        this.scheduledDate = scheduledDate;
        this.effectiveDate = scheduledDate;
        this.status = OccurrenceStatus.SCHEDULED;
    }

    public void markMaterialized(Long transactionId, Long cardPurchaseId,
                                 boolean automatic, Instant when) {
        this.transactionId = transactionId;
        this.cardPurchaseId = cardPurchaseId;
        this.autoGenerated = automatic;
        this.status = OccurrenceStatus.MATERIALIZED;
        this.materializedAt = when;
        this.failureCode = null;
        this.failureMessage = null;
    }

    public void markFailed(String code, String message) {
        this.status = OccurrenceStatus.FAILED;
        this.failureCode = code;
        this.failureMessage = message;
    }

    public void markSkipped() {
        this.status = OccurrenceStatus.SKIPPED;
    }

    /** Returns a skipped occurrence to the schedule. */
    public void markScheduled() {
        this.status = OccurrenceStatus.SCHEDULED;
        this.failureCode = null;
        this.failureMessage = null;
    }

    /**
     * Terminal reversal. Artifact links are managed by the caller: a deleted
     * transaction must be unlinked first, while a cancelled card purchase
     * keeps its link for traceability (the purchase row remains in history).
     */
    public void markReversed(Instant when) {
        this.status = OccurrenceStatus.REVERSED;
        this.reversedAt = when;
    }

    public void clearTransactionLink() {
        this.transactionId = null;
    }

    public Long getId() {
        return id;
    }

    public Long getUserId() {
        return userId;
    }

    public Commitment getCommitment() {
        return commitment;
    }

    public LocalDate getScheduledDate() {
        return scheduledDate;
    }

    public LocalDate getEffectiveDate() {
        return effectiveDate;
    }

    public void setEffectiveDate(LocalDate effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public OccurrenceStatus getStatus() {
        return status;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public Long getTransactionId() {
        return transactionId;
    }

    public Long getCardPurchaseId() {
        return cardPurchaseId;
    }

    public String getFailureCode() {
        return failureCode;
    }

    public String getFailureMessage() {
        return failureMessage;
    }

    public Instant getMaterializedAt() {
        return materializedAt;
    }

    public Instant getReversedAt() {
        return reversedAt;
    }
}
