package com.finora.api.commitment.occurrence;

import jakarta.validation.constraints.NotNull;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;

public final class OccurrenceDtos {

    private OccurrenceDtos() {
    }

    /**
     * One occurrence as the API exposes it. Calculated (not yet persisted)
     * occurrences appear as virtual SCHEDULED entries with {@code persisted}
     * false; every lifecycle action persists the identity first.
     */
    public record OccurrenceResponse(
            Long commitmentId,
            LocalDate scheduledDate,
            LocalDate effectiveDate,
            OccurrenceStatus status,
            boolean persisted,
            boolean autoGenerated,
            Long transactionId,
            Long cardPurchaseId,
            String failureCode,
            String failureMessage,
            Instant materializedAt,
            Instant reversedAt) {

        static OccurrenceResponse virtualScheduled(Long commitmentId, LocalDate date) {
            return new OccurrenceResponse(commitmentId, date, date, OccurrenceStatus.SCHEDULED,
                    false, false, null, null, null, null, null, null);
        }

        static OccurrenceResponse from(CommitmentOccurrence occurrence) {
            return new OccurrenceResponse(
                    occurrence.getCommitment().getId(),
                    occurrence.getScheduledDate(),
                    occurrence.getEffectiveDate(),
                    occurrence.getStatus(),
                    true,
                    occurrence.isAutoGenerated(),
                    occurrence.getTransactionId(),
                    occurrence.getCardPurchaseId(),
                    occurrence.getFailureCode(),
                    occurrence.getFailureMessage(),
                    occurrence.getMaterializedAt(),
                    occurrence.getReversedAt());
        }
    }

    public record OccurrencePreviewResponse(
            LocalDate from,
            LocalDate to,
            List<OccurrenceResponse> occurrences) {
    }

    public record RescheduleRequest(
            @NotNull(message = "Informe a nova data.") LocalDate newDate) {
    }

    /** Outcome of a process-due run. */
    public record ProcessDueResponse(int materialized, int failed, int alreadyProcessed) {
    }
}
