import type { AccountType, PaymentMethod, TransactionType } from '../shared/types'
import type { ConversionStatus } from '../legacy-conversions/types'

export interface TransactionCategoryRef {
  id: number
  name: string
  type: TransactionType
}

export interface TransactionAccountRef {
  id: number
  name: string
  type: AccountType
}

export interface Transaction {
  id: number
  type: TransactionType
  amount: number
  description: string
  date: string
  category: TransactionCategoryRef
  account: TransactionAccountRef | null
  paymentMethod: PaymentMethod | null
  /** Pre-card-era CREDIT entry: preserved history, not linked to any invoice. */
  legacyCredit: boolean
  /** False while an active legacy-credit conversion replaces this expense. */
  financiallyActive: boolean
  /** Latest conversion lifecycle of this source (null = never converted). */
  legacyConversionStatus: ConversionStatus | null
  /** The card purchase generated by the active conversion, when one exists. */
  generatedCardPurchaseId: number | null
  wishlistItemId: number | null
  notes: string | null
}

export interface TransactionRequest {
  type: TransactionType
  amount: number
  description: string
  date: string
  categoryId: number
  accountId?: number | null
  paymentMethod?: PaymentMethod | null
  notes?: string | null
}

export interface TransactionFilters {
  month: string
  type?: TransactionType
  categoryId?: number
  search?: string
  page: number
}
